in:
  type: file
  path_prefix: /tmp/test
  decoders:
    - type: unzip
      format: zip
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: ''
    null_string: 'NULL'
    header_line: false
    columns:
    - {name: col1, type: string}
out: {type: stdout}
